#!/bin/bash

currentDir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null 2>&1 && pwd )"
cd $currentDir

if [ ! -d "jar" ] || [ ! -r "./jar/Aura.jar" ] ; then
	if [ -x "./setup.sh" ] ; then
		./setup.sh
		echo "Launching after setup..."
	else
		echo "ERROR : Could not find the setup shell script 'setup.sh'"
		exit;
	fi
fi

cd ./jar && java -cp ./Aura.jar chatsystem.RemoteClient ../configs/config.cfg

